// This file is generated by scripts/generate-post-components.mjs
// POST_COMPONENT_MAP_MODE=prod
import type { Component } from 'svelte';

type PostComponentModule = {
	default: Component;
};

export const generatedPostComponentSlugs = [
	'are-you-interested-yet',
	'reflecting-points-across-a-line',
	'the-pythagorean-identity',
] as const;

const componentModules = import.meta.glob<PostComponentModule>(
	[
		'/src/content/posts/are-you-interested-yet.md',
		'/src/content/posts/reflecting-points-across-a-line.md',
		'/src/content/posts/the-pythagorean-identity.md',
	],
	{ eager: true }
);

const componentMap = new Map(
	Object.entries(componentModules).map(([path, module]) => {
		const filename = path.split('/').at(-1) ?? '';
		const slug = filename.replace('.md', '');
		return [slug, module.default] as const;
	})
);

export function getPostComponentBySlug(slug: string) {
	return componentMap.get(slug);
}
