// This file is generated by scripts/generate-post-components.mjs
// POST_COMPONENT_MAP_MODE=dev
import type { Component } from 'svelte';

type PostComponentModule = {
	default: Component;
};

export const generatedPostComponentSlugs = [
	'are-you-interested-yet',
	'ballistic-kinematics',
	'dont-mix-up-mixtures',
	'fractal-rhythm',
	'hexagon-three-circles',
	'lattice-path-counting',
	'pascal-triangle',
	'prime-factorization',
	'reflecting-points-across-a-line',
	'simplifying-radicals',
	'the-pythagorean-identity',
	'what-i-wish-i-knew-about-combinatorics',
] as const;

const componentModules = import.meta.glob<PostComponentModule>(
	[
		'/src/content/posts/are-you-interested-yet.md',
		'/src/content/posts/ballistic-kinematics.md',
		'/src/content/posts/dont-mix-up-mixtures.md',
		'/src/content/posts/fractal-rhythm.md',
		'/src/content/posts/hexagon-three-circles.md',
		'/src/content/posts/lattice-path-counting.md',
		'/src/content/posts/pascal-triangle.md',
		'/src/content/posts/prime-factorization.md',
		'/src/content/posts/reflecting-points-across-a-line.md',
		'/src/content/posts/simplifying-radicals.md',
		'/src/content/posts/the-pythagorean-identity.md',
		'/src/content/posts/what-i-wish-i-knew-about-combinatorics.md',
	],
	{ eager: true }
);

const componentMap = new Map(
	Object.entries(componentModules).map(([path, module]) => {
		const filename = path.split('/').at(-1) ?? '';
		const slug = filename.replace('.md', '');
		return [slug, module.default] as const;
	})
);

export function getPostComponentBySlug(slug: string) {
	return componentMap.get(slug);
}
